#!/usr/bin/env python

from lib.Ebay import Ebay
from lib.Category import Category

categories = Ebay.getCategories();

catObj = Category();
catObj.deleteTable();
catObj.createTable();
catObj.store(categories);
